/**
 * send-481 — a regression test for DOCX resume text extraction, which had none.
 *
 * WHY THIS EXISTS. `extractResumeText` (src/lib/resume/extract-text.ts) has a
 * DOCX branch that is one line: `mammoth.extractRawText({ buffer })`. No test
 * imported `mammoth` or ran that branch — `e2e/golden-path.spec.ts` says DOCX
 * extraction is excluded as binary-fixture-dependent, and the PDF suite
 * (pdf-without-canvas.test.ts) never touches it. So when Dependabot's #589
 * bumped mammoth 1.12.3 -> 1.13.0 (whose own changelog calls swapping bluebird
 * for native promises "arguably a breaking change"), a green CI run said
 * nothing about it; the only evidence was a hand-run smoke test in a scratch
 * directory. This file is what makes the next mammoth bump provable in CI.
 *
 * WHAT IT PINS, and what each assertion is for:
 *   - the text of a real .docx comes out, in reading order, with a paragraph
 *     that Word stored as three separate runs joined back into one sentence,
 *     and a non-ASCII character surviving (a change of promise type, output
 *     shape, encoding or zip handling all show up here);
 *   - the result is plain text, never zip bytes or WordprocessingML;
 *   - input that is not a readable DOCX REJECTS with an Error — an empty
 *     buffer, arbitrary bytes, a truncated upload. Both API routes that call
 *     this (api/resume/parse, api/resume-builder/import) catch the rejection
 *     and answer 422 with a fixed message; the contract they rely on is
 *     "throws, promptly, an Error" and never "resolves to garbage text that
 *     the heuristic parser then tries to read as a resume";
 *   - a supported document under an unsupported mime type is refused before
 *     any extraction.
 *
 * THE FIXTURE, tests/fixtures/resume/fictional-resume.docx (2,248 bytes), holds
 * only invented text: a fictional person, an example.com address, a 0800 000
 * 0000 phone number, a fictional employer. It was generated by a script, not
 * saved from Word, with a fixed zip timestamp so it is byte-reproducible; it
 * has headings, a bulleted list, and one paragraph split across three runs.
 * Its content, exactly as it must extract:
 *
 *   Adaeze Nwosu
 *   adaeze.nwosu@example.com | +234 800 000 0000 | Lagos, Nigeria
 *   Summary
 *   Data analyst with five years of experience in retail and logistics.
 *   Experience
 *   Senior Data Analyst, Example Analytics Ltd (2022 – 2026)
 *   Built a weekly sales dashboard used by 12 regional managers.
 *   Cut monthly reporting time from three days to one.
 *   Education
 *   B.Sc. Statistics, University of Ibadan (Ọlá Fellowship)
 *
 * Lines are compared after trimming and dropping blank lines, so a mammoth
 * release that changes how many blank lines separate paragraphs does not fail
 * this; a release that drops, reorders, splits or garbles a line does.
 *
 * No database, no network, no Supabase env: this only reads a file.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { extractResumeText } from "@/lib/resume/extract-text";

const DOCX_MIME =
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

const FIXTURE = readFileSync(
  path.join(__dirname, "../fixtures/resume/fictional-resume.docx"),
);

const EXPECTED_LINES = [
  "Adaeze Nwosu",
  "adaeze.nwosu@example.com | +234 800 000 0000 | Lagos, Nigeria",
  "Summary",
  "Data analyst with five years of experience in retail and logistics.",
  "Experience",
  "Senior Data Analyst, Example Analytics Ltd (2022 – 2026)",
  "Built a weekly sales dashboard used by 12 regional managers.",
  "Cut monthly reporting time from three days to one.",
  "Education",
  "B.Sc. Statistics, University of Ibadan (Ọlá Fellowship)",
];

function lines(text: string): string[] {
  return text
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
}

describe("extractResumeText — DOCX (send-481)", () => {
  it("CONTROL: the fixture is a real, non-trivial zip the tests can be trusted to exercise", () => {
    // A zip local-file header. If the fixture were empty, missing or replaced
    // by something else, every assertion below would be testing nothing.
    expect(FIXTURE.length).toBeGreaterThan(1000);
    expect(FIXTURE.subarray(0, 4).toString("hex")).toBe("504b0304");
  });

  it("extracts every paragraph in reading order, joins a split run, and keeps non-ASCII text", async () => {
    const text = await extractResumeText(FIXTURE, DOCX_MIME);
    expect(lines(text)).toEqual(EXPECTED_LINES);
  });

  it("returns plain text, not zip bytes or WordprocessingML", async () => {
    const text = await extractResumeText(FIXTURE, DOCX_MIME);
    expect(typeof text).toBe("string");
    expect(text).not.toContain("<w:");
    expect(text).not.toContain("word/document.xml");
    expect(text.startsWith("PK")).toBe(false);
  });

  it("rejects with an Error for bytes that are not a DOCX, instead of returning text", async () => {
    await expect(
      extractResumeText(Buffer.from("this is plainly not a docx file"), DOCX_MIME),
    ).rejects.toBeInstanceOf(Error);
  });

  it("rejects for a truncated upload (the first half of a real DOCX)", async () => {
    const half = FIXTURE.subarray(0, Math.floor(FIXTURE.length / 2));
    await expect(extractResumeText(half, DOCX_MIME)).rejects.toBeInstanceOf(Error);
  });

  it("rejects for an empty buffer", async () => {
    await expect(extractResumeText(Buffer.alloc(0), DOCX_MIME)).rejects.toBeInstanceOf(Error);
  });

  it("refuses the same bytes under a mime type it does not support, before extracting anything", async () => {
    await expect(extractResumeText(FIXTURE, "application/msword")).rejects.toThrow(
      /Unsupported resume file type/,
    );
  });
});
