/**
 * pending-job-assessment-files.ts — the IndexedDB-backed handoff that
 * carries assessment exercise files an employer picked before a real
 * `job_posting_assessments` row exists yet (send-364, scoped per-caller by
 * send-449).
 *
 * WHAT THIS COVERS AND WHAT IT DOESN'T, same split
 * tests/employer/pending-job-banner.test.ts draws for its own sessionStorage
 * equivalent: `isOwnedPendingRecord` is the one piece with no browser API in
 * it, so it's testable here without a real IndexedDB. The actual storage
 * calls (`writePendingAssessmentFiles`/`takePendingAssessmentFiles`/etc.)
 * need real IndexedDB, which this project has no jsdom/fake for (vitest
 * runs these suites under `environment: "node"` — see vitest.config.ts) —
 * those, and specifically the send-449 scoping fix itself (that two
 * different callers' keys — `CREATE_SCOPE` vs. a real job id — never
 * collide), are proven against the real browser instead, in
 * e2e/assessment-file-stage-before-save.spec.ts's own
 * "scope isolation" test: it stages a file under Create's scope, abandons
 * it, then proves a completely separate job's Edit-staged file is the ONLY
 * one that lands attached.
 */
import { describe, expect, it } from "vitest";
import { isOwnedPendingRecord, CREATE_SCOPE, type PendingAssessmentFileEntry } from "@/lib/employer/pending-job-assessment-files";

const USER_A = "11111111-1111-1111-1111-111111111111";
const USER_B = "22222222-2222-2222-2222-222222222222";

function entry(name: string): PendingAssessmentFileEntry {
  return { name, type: "text/plain", blob: new Blob(["x"]) };
}

describe("isOwnedPendingRecord", () => {
  it("returns false when there is no record at all", () => {
    expect(isOwnedPendingRecord(null, USER_A)).toBe(false);
    expect(isOwnedPendingRecord(undefined, USER_A)).toBe(false);
  });

  it("returns true when the record belongs to the current user", () => {
    const record = { userId: USER_A, files: [entry("a.txt")] };
    expect(isOwnedPendingRecord(record, USER_A)).toBe(true);
  });

  /*
   * THE CASE THIS FUNCTION EXISTS FOR — same reasoning as
   * pending-job-banner.ts's parseOwnedPendingBanner: a record staged by a
   * different signed-in user in the same origin (shared machine, or a
   * browser feature that carries storage into a new tab/profile) must
   * never be usable by this caller.
   */
  it("returns false when the record belongs to a different user", () => {
    const record = { userId: USER_B, files: [entry("a.txt")] };
    expect(isOwnedPendingRecord(record, USER_A)).toBe(false);
  });

  it("returns false for an empty-string userId", () => {
    const record = { userId: "", files: [entry("a.txt")] };
    expect(isOwnedPendingRecord(record, USER_A)).toBe(false);
    expect(isOwnedPendingRecord(record, "")).toBe(false);
  });
});

describe("CREATE_SCOPE", () => {
  /*
   * send-449's whole fix rests on this constant never being a value the
   * Edit-page caller could pass as a real job id — a job id is always a
   * UUID (job_posting_id, generated by Postgres), so a short, fixed,
   * non-UUID string can never collide with one by construction, however
   * many jobs exist. This is the one piece of the scoping guarantee that
   * IS checkable without a real IndexedDB: that the constant every
   * caller imports still holds that shape.
   */
  it("is not a valid UUID and can never collide with a real job id", () => {
    const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    expect(CREATE_SCOPE).not.toMatch(uuidPattern);
  });
});
