import type { Metadata } from "next";
import { pageMetadata } from "@/lib/seo/site";
import { LegalPage } from "@/components/marketing/legal-page";

export const metadata: Metadata = pageMetadata({
  title: "Terms of Service — Talentrah",
  description: "The terms that govern your use of Talentrah.",
  path: "/legal/terms",
});

/**
 * DRAFT — see the note in src/app/legal/privacy/page.tsx. Same caveat
 * applies here: grounded in the actual product (credits system, Paystack
 * billing) but needs a legal review pass before launch, particularly the
 * liability/disclaimer and Nigeria-specific consumer-protection sections —
 * and now, specifically, whether "Talentrah isn't a party to a mentor's
 * advice" (the Human mentorship section below) is the right liability line
 * for an actual paid transaction, and whether the platform-commission and
 * automatic-refund language there satisfies Nigerian consumer-protection
 * requirements for a marketplace taking a cut of a service it didn't perform.
 *
 * These Terms describe only what has actually shipped. Auto-apply and the
 * mentor marketplace were previously written up here as live, enableable
 * capabilities before either existed — a contract shouldn't govern features
 * that aren't there — so both were removed rather than reworded, with a note
 * to add each back once it shipped. Both have since shipped (Auto-Apply in
 * Phase 2; Mentorship 2026-09-10, PR #341/send-137) and have their own
 * sections below, grounded in src/lib/auto-apply/config.ts and
 * docs/auto-apply.md for Auto-Apply, and src/lib/mentorship/pricing.ts and
 * sweep.ts for Mentorship's commission split and no-show/refund policy — not
 * reconstructed from memory of the original, removed text. Neither section
 * states the actual cap/threshold/price numbers, which live in those files
 * specifically so a pricing or policy change doesn't also require editing a
 * legal document; each section states the invariant instead (review before
 * submit, commission is flat, a non-response auto-cancels and auto-refunds).
 */
export default function TermsOfServicePage() {
  return (
    <LegalPage eyebrow="Legal" title="Terms of Service" lastUpdated="[DATE — set at launch]">
      <p>
        These Terms govern your use of Talentrah&apos;s website and app. By
        creating an account or using Talentrah, you agree to them. If you
        don&apos;t agree, please don&apos;t use Talentrah.
      </p>

      <h2>The service</h2>
      <p>
        Talentrah is a career platform: job matching, an AI resume-tailoring
        and coaching assistant (&quot;Farah&quot;), a resume builder, a job
        application tracker, and scholarship discovery. Some features are
        free; deeper AI actions and premium templates draw from purchased
        credits or passes.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You must provide accurate information when you sign up.</li>
        <li>You&apos;re responsible for keeping your login credentials secure.</li>
        <li>You must be legally able to work in the countries you apply to jobs in.</li>
      </ul>

      <h2>AI-generated content</h2>
      <p>
        Farah&apos;s match scores, tailored resumes, gap analysis, and chat
        responses are generated by AI and are decision support, not a
        guarantee of outcome. Review anything Farah produces before you rely
        on it or submit it to an employer — you&apos;re responsible for what you
        submit under your name.
      </p>

      <h2>Applying to jobs</h2>
      <p>
        You apply to jobs yourself — Talentrah never submits an application
        on your behalf. Applying to a role listed by an external employer
        takes you to that employer&apos;s own site, where their terms and
        privacy practices apply, not ours.
      </p>

      <h2>Auto-Apply</h2>
      <p>
        Auto-Apply is off by default, and turning it on never creates a
        fully automatic mode: nothing is ever submitted without your own
        confirmation click, and it only surfaces your strongest matches for
        you to review. Confirming a match on a job posted directly on
        Talentrah creates a real application under your name, the same as
        applying yourself. Confirming a match on a job sourced from another
        company&apos;s own site or board does not submit anything there on
        your behalf — Talentrah has no way to do that — it hands you off to
        that site to apply yourself, and we record it as a link opened, not
        as an application.
      </p>

      {/*
        Approved by the founder 2026-09-01 as part of resolving build-prompt
        §10 item 19 — see docs/scholarship-sources.md's own instruction that
        the public scholarship pages surface this commitment on a legal page.
        Rewritten in this page's own second-person voice rather than pasted
        as the doc's third-person policy paragraph; every substantive
        commitment in that paragraph is carried here — facts only, official
        source as authority, no application-channel claim, provider
        takedown honoured, daily re-check.
      */}
      <h2>Scholarship listings</h2>
      <p>
        Scholarship listings on Talentrah are facts we&apos;ve verified against
        each provider&apos;s own official page — provider, eligibility, funding,
        and application deadline — never a provider&apos;s own descriptive text,
        always linked back to that official source, which remains the
        authority on current terms. Talentrah isn&apos;t the application channel
        for any scholarship: you apply directly with the provider. We only
        source facts from official pages whose terms and robots.txt permit
        it, or enter them ourselves after checking them by hand, and we
        re-check listings daily so a closed scholarship stops appearing. If a
        provider asks us to remove or correct a listing, we will.
      </p>

      <h2>Credits, passes, and payments</h2>
      <p>
        Credits and passes are purchased in Naira through Paystack and are
        consumed as described at the time of purchase. Purchases are
        generally non-refundable once a credit-consuming action has been
        performed, except where required by law. A pass paid for by card
        renews automatically until you cancel it, which you can do at any
        time from your billing page; a pass paid for by any other method is
        one-time and does not renew.
      </p>

      <h2>Human mentorship</h2>
      <p>
        Mentorship connects you directly with a vetted human mentor for the
        moments Farah steps back from — things like a mock interview or
        negotiating a specific offer. Mentors apply and are reviewed before
        they can be booked, but that review doesn&apos;t make Talentrah a
        party to a session&apos;s advice: what a mentor tells you is their
        own judgment, not ours. A paid session is billed in Naira through
        Paystack at the price the mentor sets — some mentors volunteer their
        time for free — never through Credits, and Talentrah keeps a flat
        platform commission from any paid session. If a mentor doesn&apos;t
        confirm a booked session at least 24 hours before it&apos;s
        scheduled to start, the session is cancelled automatically and any
        payment already made is refunded automatically.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Don&apos;t use Talentrah to post false information, impersonate someone
        else, scrape or resell our data, or interfere with the service&apos;s
        normal operation.
      </p>

      <h2>Disclaimer and liability</h2>
      <p>
        Talentrah is provided &quot;as is.&quot; We work to keep match scores, job
        listings, and AI outputs accurate and useful, but we don&apos;t guarantee
        job placement, interview outcomes, or that any listing is free of
        error. To the fullest extent permitted by law, Talentrah isn&apos;t liable
        for indirect or consequential losses arising from your use of the
        service.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these Terms as the product changes. We&apos;ll post the
        updated version here with a new &quot;last updated&quot; date, and where a
        change is material we&apos;ll make a reasonable effort to notify you
        directly.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these Terms can be sent to{" "}
        <a href="/contact">our contact page</a>.
      </p>
    </LegalPage>
  );
}
