import type { Metadata } from "next";
import { LegalPage } from "@/components/marketing/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service — Talentrah",
  description: "The terms that govern your use of Talentrah.",
};

/**
 * DRAFT — see the note in src/app/legal/privacy/page.tsx. Same caveat
 * applies here: grounded in the actual product (credits system, Paystack
 * billing, auto-apply, mentor marketplace) but needs a legal review pass
 * before launch, particularly the liability/disclaimer and Nigeria-specific
 * consumer-protection sections.
 */
export default function TermsOfServicePage() {
  return (
    <LegalPage eyebrow="Legal" title="Terms of Service" lastUpdated="[DATE — set at launch]">
      <p>
        These Terms govern your use of Talentrah&apos;s website and app. By
        creating an account or using Talentrah, you agree to them. If you
        don&apos;t agree, please don&apos;t use Talentrah.
      </p>

      <h2>The service</h2>
      <p>
        Talentrah is a career platform: job matching, an AI resume-tailoring
        and coaching assistant (&quot;Farah&quot;), a job application tracker, and
        (where enabled) an optional auto-apply feature and a mentor
        marketplace. Some features are free; deeper AI actions and premium
        features draw from purchased credits or passes.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You must provide accurate information when you sign up.</li>
        <li>You&apos;re responsible for keeping your login credentials secure.</li>
        <li>You must be legally able to work in the countries you apply to jobs in.</li>
      </ul>

      <h2>AI-generated content</h2>
      <p>
        Farah&apos;s match scores, tailored resumes, gap analysis, and chat
        responses are generated by AI and are decision support, not a
        guarantee of outcome. Review anything Farah produces before you rely
        on it or submit it to an employer — you&apos;re responsible for what you
        submit under your name.
      </p>

      <h2>Auto-apply</h2>
      <p>
        If you enable auto-apply, Talentrah submits applications on your
        behalf based on preferences you set, up to any caps and review steps
        described in the feature itself. You can turn auto-apply off, and
        review or cancel a pending submission, at any time before it&apos;s sent.
      </p>

      <h2>Credits, passes, and payments</h2>
      <p>
        Credits and passes are purchased in Naira through Paystack and are
        consumed as described at the time of purchase. Purchases are
        generally non-refundable once a credit-consuming action has been
        performed, except where required by law. Mentor sessions are booked
        and paid separately from the credits system, directly with the
        mentor.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Don&apos;t use Talentrah to post false information, impersonate someone
        else, scrape or resell our data, or interfere with the service&apos;s
        normal operation.
      </p>

      <h2>Disclaimer and liability</h2>
      <p>
        Talentrah is provided &quot;as is.&quot; We work to keep match scores, job
        listings, and AI outputs accurate and useful, but we don&apos;t guarantee
        job placement, interview outcomes, or that any listing is free of
        error. To the fullest extent permitted by law, Talentrah isn&apos;t liable
        for indirect or consequential losses arising from your use of the
        service.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these Terms as the product changes. We&apos;ll post the
        updated version here with a new &quot;last updated&quot; date, and where a
        change is material we&apos;ll make a reasonable effort to notify you
        directly.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these Terms can be sent to{" "}
        <a href="/contact">our contact page</a>.
      </p>
    </LegalPage>
  );
}
