import type { Metadata } from "next";
import { pageMetadata } from "@/lib/seo/site";
import { LegalPage } from "@/components/marketing/legal-page";

export const metadata: Metadata = pageMetadata({
  title: "Terms of Service — Talentrah",
  description: "The terms that govern your use of Talentrah.",
  path: "/legal/terms",
});

/**
 * DRAFT — see the note in src/app/legal/privacy/page.tsx. Same caveat
 * applies here: grounded in the actual product (credits system, Paystack
 * billing) but needs a legal review pass before launch, particularly the
 * liability/disclaimer and Nigeria-specific consumer-protection sections.
 *
 * These Terms describe only what has actually shipped. Auto-apply (Phase 2)
 * and the mentor marketplace (Phase 3) were previously written up here as
 * live, enableable capabilities — they don't exist and can't be enabled, so
 * they're gone rather than reworded. A contract shouldn't govern features
 * that aren't there: it misleads users about what they're agreeing to, and
 * on the auto-apply clause specifically it described Talentrah acting on a
 * user's behalf in a way it currently cannot. When either ships, add its
 * section back at that point.
 */
export default function TermsOfServicePage() {
  return (
    <LegalPage eyebrow="Legal" title="Terms of Service" lastUpdated="[DATE — set at launch]">
      <p>
        These Terms govern your use of Talentrah&apos;s website and app. By
        creating an account or using Talentrah, you agree to them. If you
        don&apos;t agree, please don&apos;t use Talentrah.
      </p>

      <h2>The service</h2>
      <p>
        Talentrah is a career platform: job matching, an AI resume-tailoring
        and coaching assistant (&quot;Farah&quot;), a resume builder, a job
        application tracker, and scholarship discovery. Some features are
        free; deeper AI actions and premium templates draw from purchased
        credits or passes.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You must provide accurate information when you sign up.</li>
        <li>You&apos;re responsible for keeping your login credentials secure.</li>
        <li>You must be legally able to work in the countries you apply to jobs in.</li>
      </ul>

      <h2>AI-generated content</h2>
      <p>
        Farah&apos;s match scores, tailored resumes, gap analysis, and chat
        responses are generated by AI and are decision support, not a
        guarantee of outcome. Review anything Farah produces before you rely
        on it or submit it to an employer — you&apos;re responsible for what you
        submit under your name.
      </p>

      <h2>Applying to jobs</h2>
      <p>
        You apply to jobs yourself — Talentrah never submits an application
        on your behalf. Applying to a role listed by an external employer
        takes you to that employer&apos;s own site, where their terms and
        privacy practices apply, not ours.
      </p>

      <h2>Credits, passes, and payments</h2>
      <p>
        Credits and passes are purchased in Naira through Paystack and are
        consumed as described at the time of purchase. Purchases are
        generally non-refundable once a credit-consuming action has been
        performed, except where required by law. A pass paid for by card
        renews automatically until you cancel it, which you can do at any
        time from your billing page; a pass paid for by any other method is
        one-time and does not renew.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Don&apos;t use Talentrah to post false information, impersonate someone
        else, scrape or resell our data, or interfere with the service&apos;s
        normal operation.
      </p>

      <h2>Disclaimer and liability</h2>
      <p>
        Talentrah is provided &quot;as is.&quot; We work to keep match scores, job
        listings, and AI outputs accurate and useful, but we don&apos;t guarantee
        job placement, interview outcomes, or that any listing is free of
        error. To the fullest extent permitted by law, Talentrah isn&apos;t liable
        for indirect or consequential losses arising from your use of the
        service.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these Terms as the product changes. We&apos;ll post the
        updated version here with a new &quot;last updated&quot; date, and where a
        change is material we&apos;ll make a reasonable effort to notify you
        directly.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these Terms can be sent to{" "}
        <a href="/contact">our contact page</a>.
      </p>
    </LegalPage>
  );
}
