/**
 * The factory-mock ratchet's ALLOWLIST (TEST-MOCK-1): the hand-written `vi.mock("<module>", () => ({ ... }))` factories still in the tree for the scoped shared modules (tests/support/mock-factory-ratchet.ts), keyed
 * "<module> :: <test file>". It starts as today's list (the vi.mock audit, reports/S3/34, with the ten chat-gate route tests already moved onto safeChatGate) and ONLY EVER SHRINKS: moving a file onto a shared helper or an
 * importOriginal spread (or deleting it) removes its entry here and lowers ALLOWLIST_CEILING in the same commit. tests/ci/mock-factory-ratchet.test.ts holds this exactly equal to what is really in the tree, so a new
 * hand-written factory fails, a converted file that is still listed fails, and the ceiling can never exceed what it started at.
 */
export const ALLOWLIST: Record<string, number> = {
  "@/lib/api/rate-limit :: tests/resume-builder/import-route-parse-fallback.test.ts": 1,
  "@/lib/api/rate-limit :: tests/tailoring/malformed-body.test.ts": 1,
  "@/lib/api/rate-limit :: tests/tailoring/route-credits-balance.test.ts": 1,
  "@/lib/auth/require-user :: tests/mentorship/own-profile-details-read.test.ts": 1,
  "@/lib/credits/gate-events :: tests/farah/chat-done-balance.test.ts": 1,
  "@/lib/credits/gate-events :: tests/farah/free-claim-gate.test.ts": 1,
  "@/lib/credits/gate-events :: tests/farah/message-charge-agreement.test.ts": 1,
  "@/lib/credits/gate-events :: tests/farah/next-free-message.test.ts": 1,
  "@/lib/credits/gate-events :: tests/resume-builder/rewrite-bullet-balance.test.ts": 1,
  "@/lib/credits/gate-events :: tests/tailoring/commit-balance.test.ts": 1,
  "@/lib/credits/spend :: tests/demo/jd-demo-no-balance.test.tsx": 1,
  "@/lib/credits/spend :: tests/farah/chat-done-balance.test.ts": 1,
  "@/lib/credits/spend :: tests/farah/chat-route-failed-requests-charge-nothing.test.ts": 1,
  "@/lib/credits/spend :: tests/farah/free-claim-end-to-end.test.ts": 1,
  "@/lib/credits/spend :: tests/farah/free-claim-gate.test.ts": 1,
  "@/lib/credits/spend :: tests/farah/message-charge-agreement.test.ts": 1,
  "@/lib/credits/spend :: tests/farah/next-free-message-end-to-end.test.ts": 1,
  "@/lib/credits/spend :: tests/farah/next-free-message.test.ts": 1,
  "@/lib/credits/spend :: tests/resume-builder/rewrite-bullet-balance.test.ts": 1,
  "@/lib/credits/spend :: tests/tailoring/commit-balance.test.ts": 1,
  "@/lib/credits/spend :: tests/talent-directory/verification-runner-flagged.test.ts": 1,
  "@/lib/farah/client :: tests/farah/chat-route-allowance-skip.test.ts": 1,
  "@/lib/farah/client :: tests/farah/chat-route-failed-requests-charge-nothing.test.ts": 1,
  "@/lib/farah/client :: tests/farah/chat-route-spend-ceiling.test.ts": 1,
  "@/lib/farah/session-events :: tests/farah/chat-route-failed-requests-charge-nothing.test.ts": 1,
  "@/lib/farah/session-events :: tests/farah/chat-route-spend-ceiling.test.ts": 1,
  "@/lib/farah/spend-tally :: tests/farah/chat-route-failed-requests-charge-nothing.test.ts": 1,
  "@/lib/farah/spend-tally :: tests/farah/chat-route-spend-ceiling.test.ts": 1,
  "@/lib/farah/spend-tally :: tests/setup.ts": 1,
  "@/lib/flags/read :: tests/auto-apply-digest/flag-gate.test.ts": 1,
  "@/lib/flags/read :: tests/auto-apply-digest/send.test.ts": 1,
  "@/lib/flags/read :: tests/digest/flag-gate.test.ts": 1,
  "@/lib/flags/read :: tests/digest/proactive-alert-exclusion.test.ts": 1,
  "@/lib/flags/read :: tests/digest/verification-gate.test.ts": 1,
  "@/lib/flags/read :: tests/jobs/enrich-thin-stub-guard.test.ts": 1,
  "@/lib/flags/read :: tests/jobs/enrich-thin.test.ts": 1,
  "@/lib/flags/read :: tests/jobs/supersession-ingest.test.ts": 1,
  "@/lib/flags/read :: tests/notifications/proactive-match-alert-eligibility.test.ts": 1,
  "@/lib/flags/read :: tests/notifications/proactive-match-alert-gates.test.ts": 1,
  "@/lib/flags/read :: tests/notifications/win-back-eligibility.test.ts": 1,
  "@/lib/llm :: tests/employer/draft-job-action.test.ts": 1,
  "@/lib/llm :: tests/employer/draft-job.test.ts": 1,
  "@/lib/llm :: tests/employer/job-import/extract.test.ts": 1,
  "@/lib/llm :: tests/resume/llm-fallback-new-fields.test.ts": 1,
  "@/lib/llm :: tests/screening/farah-review-llm-failure.test.ts": 1,
  "@/lib/llm :: tests/tailoring/bullets-consumers.test.tsx": 1,
  "@/lib/llm :: tests/tailoring/cache-version-compat.test.ts": 1,
  "@/lib/llm :: tests/tailoring/fabrication-backstop.test.ts": 1,
  "@/lib/llm :: tests/tailoring/jd-truncation.test.ts": 1,
  "@/lib/llm :: tests/tailoring/new-fields-preserved.test.ts": 1,
  "@/lib/llm :: tests/tailoring/result-cache.test.ts": 1,
  "@/lib/llm :: tests/tailoring/tailoring-bullets.test.tsx": 1,
  "@/lib/llm :: tests/talent-directory/grader-injection-guard.test.ts": 1,
  "@/lib/llm :: tests/talent-directory/grader-stub-provider.test.ts": 1,
  "@/lib/llm :: tests/talent-directory/review-method-proof.test.ts": 1,
  "@/lib/passes/entitlement :: tests/farah/chat-done-balance.test.ts": 1,
  "@/lib/passes/entitlement :: tests/farah/free-claim-gate.test.ts": 1,
  "@/lib/passes/entitlement :: tests/farah/message-charge-agreement.test.ts": 1,
  "@/lib/passes/entitlement :: tests/farah/next-free-message-wiring.test.ts": 1,
  "@/lib/passes/entitlement :: tests/farah/next-free-message.test.ts": 1,
  "@/lib/passes/entitlement :: tests/resume-builder/rewrite-bullet-balance.test.ts": 1,
  "@/lib/passes/entitlement :: tests/tailoring/commit-balance.test.ts": 1,
};

/** Must equal the sum of ALLOWLIST. Lower it with every conversion; raising it is a visible, reviewed act. */
export const ALLOWLIST_CEILING = 62;

/** How many hand-written factories the scoped modules had when the ratchet was introduced. Never changes: the ceiling may not exceed it. */
export const INITIAL_FACTORIES = 149;
