/**
 * The ONE definition of reviewer-addressed commentary and of the public text columns it must never appear in (#704).
 *
 * A sourcing pass once wrote notes to the reviewer ("a human should confirm this date…", "NOT independently confirmed") into columns an applicant reads, and the
 * listing was approved and went public with them. Commentary belongs in `moderation_note` and nowhere else. Three things read THIS file so they cannot drift:
 * the approval guard (src/lib/admin/moderation/actions.ts), the source-config test, and the read-only query a person runs before and after a hand-run data fix
 * (`reviewerCommentaryCountsQuery`, recorded in that fix's RECORD).
 *
 * THE LIST IS SMALL ON PURPOSE. Only phrases that are unmistakably addressed to a reviewer. "before publishing" would flag a scholarship for journalists, "this pass"
 * is a Talentrah product word, "could not confirm" appears in honest eligibility text ("the registry could not confirm…"): none is a trigger on its own.
 * Provenance wording ("Officially confirmed (fetched … from the … application form)") says where a fact came from and is never flagged.
 */
export const REVIEWER_PHRASES = [
  "a human should",
  "not independently confirmed",
  "not machine-verified",
  "needs a human to confirm",
  "see moderation_note",
] as const;

/** Public text columns that are checked. A scholarship's text an applicant can read, on the card, the page, the landing pages, the blog embed or the SEO description. */
export const CHECKED_PUBLIC_TEXT_COLUMNS = [
  "provider",
  "program_name",
  "host_institution",
  "field_tags",
  "funding_covers",
  "eligibility_nationalities",
  "eligibility_prior_degree",
  "eligibility_age",
  "eligibility_other",
  "source_name",
  "deadline_note",
] as const;

/**
 * Columns typed as text that are deliberately NOT checked, each with the reason. A new public text column that is in neither list fails
 * tests/scholarships/reviewer-commentary.test.ts, so it cannot be added without deciding.
 */
export const EXCLUDED_PUBLIC_TEXT_COLUMNS: Record<string, string> = {
  id: "A uuid generated by the database; it holds no prose.",
  application_deadline: "A calendar date; the database refuses anything that is not one.",
  close_time: "A time of day; the database refuses anything that is not one.",
  close_tz: "An IANA time-zone name, validated by the close-instant trigger.",
  deadline_verified_at: "A timestamp; it holds no prose.",
  official_url: "A link the operator pastes; it is not prose an applicant reads as a statement.",
  dedup_fingerprint: "An internal hash, never selected by a public query.",
  moderation_note:
    "Where reviewer commentary belongs, and no page selects it. NOTE: the anon role can still read it through the API on verified rows (table-level SELECT grant), so it is not private yet; that is an open owner decision, not something this list settles.",
};

export type CommentaryFinding = { column: string; phrase: string };

/**
 * What the check compares: lower-case; straight quotes; one ordinary hyphen; every run of whitespace (non-breaking spaces and line breaks included) as one space;
 * and the `*` and `_` emphasis characters removed. The last matters because the text fields render bold and italic: "**NOT** independently confirmed" reads as the
 * phrase to a visitor and must read as the phrase here. The same normalisation is used everywhere (and `reviewerCommentaryCountsQuery` strips the same two characters
 * in SQL), so no consumer matches differently from another.
 */
export function normaliseForCheck(text: string): string {
  return text
    .toLowerCase()
    .replace(/[‘’‚‛]/g, "'")
    .replace(/[“”„‟]/g, '"')
    .replace(/[‐‑‒–—−]/g, "-")
    .replace(/[*_]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * A phrase as a regular expression source for TEXT THAT HAS ALREADY BEEN NORMALISED (so its underscores are gone): runs of whitespace and hyphen variants are
 * tolerated, and an underscore in the phrase matches nothing or a space. Same source in JS and Postgres.
 */
export function phraseRegex(phrase: string): string {
  return phrase
    .replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    .replace(/ /g, "\\s+")
    .replace(/-/g, "[-\\s‐‑‒–—−]")
    .replace(/_/g, "\\s*");
}

type Row = Record<string, string | readonly string[] | null | undefined>;

/**
 * Every (column, phrase) pair found in the checked public text columns of one listing. Columns not in the checked list (the review note above all) are ignored.
 * `phrases` exists so a test can prove that dropping a phrase from the list stops its field being flagged.
 */
export function findReviewerCommentary(row: Row, opts: { phrases?: readonly string[] } = {}): CommentaryFinding[] {
  const phrases = opts.phrases ?? REVIEWER_PHRASES;
  const found: CommentaryFinding[] = [];
  for (const column of CHECKED_PUBLIC_TEXT_COLUMNS) {
    const value = row[column];
    if (value == null) continue;
    const text = normaliseForCheck(typeof value === "string" ? value : value.join(" ; "));
    for (const phrase of phrases) {
      if (new RegExp(phraseRegex(phrase), "i").test(text)) found.push({ column, phrase });
    }
  }
  return found;
}

/**
 * The read-only query for a hand-run data fix: how many scholarships carry each phrase, and in which columns. Run it before and after, and record the two counts
 * per phrase in the fix's RECORD. It reads the whole table and changes nothing.
 */
export function reviewerCommentaryCountsQuery(): string {
  const cols = CHECKED_PUBLIC_TEXT_COLUMNS.map((c) => `('${c}')`).join(", ");
  const phr = REVIEWER_PHRASES.map((p) => `('${p}', '${phraseRegex(p)}')`).join(",\n  ");
  return `-- READ ONLY: scholarships carrying each reviewer phrase in a public text column (counts and column names, never the text).
with cols(c) as (values ${cols}),
phr(p, rx) as (values
  ${phr}),
kv as (select s.id, e.key, regexp_replace(e.value, '[*_]', '', 'g') as value from public.scholarships s, jsonb_each_text(to_jsonb(s)) e where e.key in (select c from cols))
select phr.p as phrase, count(distinct kv.id) as rows, coalesce(string_agg(distinct kv.key, ', '), '') as columns
from phr left join kv on kv.value ~* phr.rx
group by phr.p order by phr.p;`;
}

const COLUMN_LABEL: Record<string, string> = {
  provider: "Provider",
  program_name: "Programme name",
  host_institution: "Host institution",
  field_tags: "Field tags",
  funding_covers: "Funding covers",
  eligibility_nationalities: "Eligible nationalities",
  eligibility_prior_degree: "Eligibility prior degree",
  eligibility_age: "Eligibility age",
  eligibility_other: "Eligibility other",
  source_name: "Source name",
  deadline_note: "Deadline note",
};

/** What the operator reads when approval is refused: the field and the phrase for every finding, and what to do. */
export function commentaryRefusalMessage(programName: string, findings: CommentaryFinding[]): string {
  const items = findings.map((f) => `${COLUMN_LABEL[f.column] ?? f.column} contains “${f.phrase}”`).join("; ");
  return `Can't approve “${programName}”: ${items}. That is wording for a reviewer, not listing text an applicant should read. Move it to the review note, fix the listing, and approve again.`;
}
