import { readdirSync } from "node:fs";
import { join } from "node:path";

/**
 * Emit the SQL that answers "which committed migrations are not recorded as
 * applied here" — to be run against either project through the Supabase MCP
 * connector.
 *
 * ── WHY THIS EXISTS ───────────────────────────────────────────────────────
 *
 * 0066 sat committed-but-unapplied on production for hours. Its code shipped,
 * the column was never created, and the feature silently did nothing on the
 * live site. Nobody noticed because there was no diff anyone could run and
 * believe: `schema_migrations` on production holds three naming conventions,
 * and on CI it is missing 25 rows for schema that is demonstrably present. A
 * naive comparison drowns one real gap in eleven false ones — which is worse
 * than no comparison, because it teaches people to ignore the output.
 *
 * ── WHY IT PRINTS SQL INSTEAD OF CONNECTING ───────────────────────────────
 *
 * Two reasons, one discovered the hard way.
 *
 * The first version used the service-role client and failed: PostgREST exposes
 * only the schemas it is configured for, and `supabase_migrations` is not one
 * of them — `Invalid schema: supabase_migrations`. Reaching it would mean
 * adding a `public` function to wrap a tooling query, which is real schema
 * surface for a housekeeping concern.
 *
 * The second reason is the one that makes this the better design anyway.
 * PRODUCTION is the project that most needs auditing, and CLAUDE.md is
 * explicit that production work goes through the MCP connector precisely so a
 * credential never lands on disk. A script that connected would either be
 * useless for production or would want the one key nobody should be storing.
 * Printing SQL needs no credential at all, and audits either project.
 *
 * ── WHY IT DOES NOT "FIX" THE LEDGER ──────────────────────────────────────
 *
 * Rewriting the recorded names to match the filenames was the obvious
 * alternative and it is the wrong one. The repo's position, stated in three
 * migration headers, is that an applied migration is history: 0060 kept its
 * colliding number because its header carries an md5 of the recorded
 * statements, 0061 documents its own name mismatch as "cosmetic and
 * deliberate" and says in capitals not to re-apply it to fix the name, and
 * 0062 exists at all because editing an applied migration was refused.
 *
 * The problem was never that the record is untidy. It is that nothing could
 * read it. This reads it.
 *
 *   npm run audit-migrations           # prints the query
 *   npm run audit-migrations -- --list # prints what it considers committed
 */

const MIGRATIONS_DIR = join(process.cwd(), "supabase", "migrations");

/**
 * Not a migration, and must not be reported as unapplied. 0000 is a snapshot
 * of the schema as it stood at 0026, written so later changes have a
 * reviewable baseline; its own header says it is not to be run, and running it
 * would fail on every object it describes.
 */
const NOT_A_MIGRATION = new Set(["0000_baseline_schema"]);

/**
 * Recorded under a name that is not its filename, deliberately.
 *
 * Only 0061, and only because its file explains why: it shipped as
 * 0060_course_recommendations, collided with 0060_admin_identity from another
 * branch the same morning, and was renumbered AFTER being applied to both
 * projects. Supabase keys the table on `version`, and the two 0060 rows carry
 * different versions, so nothing is ambiguous — only the label is stale,
 * permanently and on purpose.
 *
 * An entry here claims a mismatch was DECIDED rather than missed. Adding one
 * to silence this script would be the failure it exists to prevent, so each
 * needs its reasoning written above it.
 */
const KNOWN_ALIASES: Record<string, string> = {
  "0061_course_recommendations": "0060_course_recommendations",
};

function committedMigrations(): string[] {
  return readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith(".sql"))
    .map((f) => f.replace(/\.sql$/, ""))
    .filter((n) => !NOT_A_MIGRATION.has(n))
    .sort();
}

function buildQuery(names: string[]): string {
  const values = names.map((n) => `('${n.replace(/'/g, "''")}')`).join(",\n    ");
  const aliases = Object.entries(KNOWN_ALIASES)
    .map(([file, recorded]) => `('${file}','${recorded}')`)
    .join(", ");

  return `-- Committed migrations vs what this project records as applied.
-- Generated by scripts/audit-migrations.ts — run through the Supabase MCP
-- connector against production (nytwbbzfpytctjsoczzq) or CI (dozaffzgqkbarxtlclsj).
--
-- A row of 'MISSING' means the LEDGER IS SILENT, not that the change is absent.
-- Check for the schema itself — the table, column, function or grant the
-- migration creates — before concluding it never ran. A project restored from a
-- snapshot rather than replayed has the schema WITHOUT the record, which is
-- exactly the state CI is in for 0026-0050.
with committed(name) as (values
    ${values}
),
alias(file_name, recorded_name) as (values ${aliases}),
applied as (select name from supabase_migrations.schema_migrations where name is not null)
select
  c.name as migration,
  case
    when exists (select 1 from applied a where a.name = c.name)
      then 'applied'
    when exists (
      select 1 from alias al join applied a on a.name = al.recorded_name
      where al.file_name = c.name
    ) then 'applied under a documented alias'
    when exists (
      select 1 from applied a
      where regexp_replace(a.name, '^[0-9]{4}_', '') = regexp_replace(c.name, '^[0-9]{4}_', '')
    ) then 'applied without its numeric prefix'
    else 'MISSING'
  end as status
from committed c
order by
  case when exists (select 1 from applied a where a.name = c.name) then 2 else 1 end,
  c.name;`;
}

const names = committedMigrations();

if (process.argv.includes("--list")) {
  console.log(names.join("\n"));
  console.log(`\n${names.length} committed migrations (excluding the baseline snapshot)`);
} else {
  console.log(buildQuery(names));
}
