-- 0246: employer job feeds, database part: the table that holds an employer's feed (its address, its proof of control of the site, its consent, its state), a small audit table for the connect
-- and check attempts, and three columns on job_postings that mark a posting as imported. PR 1 of the Employer job import (plan: reports/S1/2026-10-08-employer-job-import-plan.md, approved by the owner on
-- 8 Oct 2026; number 0246 assigned by the owner).
--
-- WHAT IT ADDS (additive, with ONE replaced function):
--   1. public.employer_job_feeds: one row per (organisation, host) feed. Members of the organisation READ their own row (the site-control code is theirs to see); nobody writes it from a client.
--      Every write is a Server Action or the daily route running as the service role after its own membership/verification checks (the 0026-0030 rule: a row policy does not restrict columns, so
--      the table has a SELECT grant by column and no INSERT, UPDATE or DELETE grant at all). A feed is never hard-deleted by a client: removing it sets state = 'removed' (the whole sync state lives in the one `state` column plus problem_since, grace_ends_at, the two counters and the two warning stamps).
--   2. public.employer_job_feed_attempts: who tried to connect or check which host, when, and with what result (never the code). No client access of any kind; the rate limits and the "failed attempts
--      per host per day" count read it as the service role.
--   3. job_postings.import_feed_id, .import_key, .employer_closed_at. An imported posting is an `internal` row of the employer's organisation (so the verified-organisation gate of 0027 applies by itself)
--      carrying import_feed_id. import_feed_id is publicly readable (the pages need it to treat the job as link-out); import_key and employer_closed_at are not (the sync's own bookkeeping). No client may write
--      any of the three: no UPDATE column grant covers them, and the INSERT policy "org members can manage their org's internal postings" now also requires all three to be null (authenticated holds a
--      TABLE-level INSERT on job_postings, so a column grant cannot close INSERT; the policy's WITH CHECK is where this table already closes it for the moderation and claim columns, 0221). Constraints: import_feed_id and import_key are both set or both null, an imported posting is `internal`, and (import_feed_id, import_key)
--      is unique, so a repeated sync cannot make a duplicate.
--      The UPDATE policy "org members can update their org's internal postings" ALSO requires import_feed_id to be null (USING and WITH CHECK): without it any member could edit an imported row through the API
--      (reopen a job the sync, the 14-day grace, an operator or the employer's own removal had closed; rewrite its title, description or apply link). Close and Hide of imported rows are service-role Server
--      Actions after a membership check.
--   4. public.org_job_widget REPLACED (create or replace, same signature, same grants): the widget never lists an imported posting (`and j.import_feed_id is null`). This is the one change to existing
--      behaviour, and it changes nothing today because no posting has import_feed_id set.
--
-- WHAT IT DOES NOT DO. No sync engine, no route, no page: those are PRs 2 to 5. Nothing reads these tables yet, so applying this to production changes no page. The feature is also behind a server-side
-- switch (EMPLOYER_JOB_FEEDS_ENABLED, default off) and an organisation allow-list (EMPLOYER_JOB_FEEDS_ORGS), both outside the database.
--
-- ORDER. Additive, so it is applied to preview and then production BEFORE the code that uses it merges (docs/production-migration-apply.md). The exact undo is supabase/rollbacks/0246_employer_job_feeds.rollback.sql,
-- which refuses to run while any imported posting exists.
--
-- PER-REQUEST COST. None: no existing read path changes except the widget's one extra predicate on an indexed table.

-- Fail fast instead of queueing behind a long query on job_postings: the migration is retried, not waited for.
set local lock_timeout = '3s';

-- 1. The feed ---------------------------------------------------------------------------------------------------------------------------------
create table public.employer_job_feeds (
  id                          uuid primary key default gen_random_uuid(),
  organization_id             uuid not null references public.organizations (id) on delete cascade,
  kind                        text not null default 'schema_org' check (kind in ('schema_org')),
  url                         text not null check (url ~ '^https://[^/[:space:]]+' and char_length(url) <= 2048),
  host                        text not null check (host = lower(host) and host !~ '[/[:space:]@:]' and char_length(host) between 3 and 253),
  -- The site-control code: 32 random bytes from the system CSPRNG, base64url (43 characters), generated by the server, one per (organisation, host). It is public once placed on the site; the risk is
  -- guessability and reuse, not leakage. "Make a new code" replaces it.
  site_proof_code             text not null check (site_proof_code ~ '^[A-Za-z0-9_-]{43,}$'),
  proof_kind                  text check (proof_kind in ('well_known', 'meta')),
  proof_verified_at           timestamptz,
  consent_text_version        integer not null check (consent_text_version >= 1),
  consented_by                uuid references public.profiles (id) on delete set null,
  consented_at                timestamptz not null,
  consent_host                text not null check (consent_host = host),
  -- The host column is the host part of the address, so a feed's host cannot differ from the page that is fetched (no userinfo, no port: a URL that does not match the pattern fails the check).
  constraint employer_job_feeds_host_is_url_host check (substring(url from '^https://([^/?#:@]+)([/?#]|$)') is not null and host = lower(substring(url from '^https://([^/?#:@]+)([/?#]|$)'))),
  -- The sync state (S3's design, reports/S3/47 section 3b). One column, one meaning: the page and the daily route read only `state`. Every transition is ONE conditional UPDATE by the service role.
  state                       text not null default 'active' check (state in ('active', 'paused_proof', 'paused_unreadable', 'paused_employer', 'disabled_operator', 'removed')),
  state_reason                text check (state_reason ~ '^[a-z_]{1,40}$'),
  -- problem_since is the FIRST failed update of the current streak (null when healthy); the 14-day grace runs from it, so the two-misses rule never lengthens the employer's clock.
  problem_since               timestamptz,
  grace_ends_at               timestamptz,
  consecutive_proof_misses    integer not null default 0 check (consecutive_proof_misses >= 0),
  consecutive_unreadable      integer not null default 0 check (consecutive_unreadable >= 0),
  last_success_at             timestamptz,
  -- The two warning emails, each sent once per streak (the daily run sends one only while its stamp is null); cleared on success.
  warning_1_sent_at           timestamptz,
  warning_2_sent_at           timestamptz,
  last_synced_at              timestamptz,
  last_status                 text check (last_status ~ '^[a-z_]{1,40}$'),
  last_counts                 jsonb,
  last_error                  text check (char_length(last_error) <= 200),
  robots_checked_at           timestamptz,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  constraint employer_job_feeds_streak_has_grace check ((problem_since is null) = (grace_ends_at is null) and (grace_ends_at is null or grace_ends_at >= problem_since)),
  constraint employer_job_feeds_proof_pause_has_streak check (state not in ('paused_proof', 'paused_unreadable') or problem_since is not null)
);

-- One live feed per (organisation, host) and per address; a removed feed frees both, so an employer can connect the same page again.
create unique index employer_job_feeds_one_per_org_host on public.employer_job_feeds (organization_id, host) where state <> 'removed';
create unique index employer_job_feeds_url_unique on public.employer_job_feeds (url) where state <> 'removed';

comment on table public.employer_job_feeds is
  '0246: an employer''s job feed (its own careers page): address, proof of control of the site, consent record, state. Members of the organisation read their own rows; every write is the service role after membership and verification checks. Never hard-deleted by a client (state = removed).';
comment on column public.employer_job_feeds.site_proof_code is
  '0246: the per-(organisation, host) site-control code, 32 random bytes base64url. Public once placed on the site; readable only by members of the organisation. Never in a log line, an error message, an analytics event or a URL.';

create index employer_job_feeds_org_idx on public.employer_job_feeds (organization_id);
create index employer_job_feeds_due_idx on public.employer_job_feeds (last_synced_at nulls first) where state = 'active';
create index employer_job_feeds_grace_idx on public.employer_job_feeds (grace_ends_at) where state in ('paused_proof', 'paused_unreadable');

alter table public.employer_job_feeds enable row level security;

-- Column grants first: nothing by default, then exactly what a member may read. No INSERT, UPDATE or DELETE grant exists for any API role.
revoke all on table public.employer_job_feeds from public, anon, authenticated;
grant select (
  id, organization_id, kind, url, host, site_proof_code, proof_kind, proof_verified_at, consent_text_version, consented_by, consented_at, consent_host,
  state, state_reason, problem_since, grace_ends_at, consecutive_proof_misses, consecutive_unreadable, last_success_at, warning_1_sent_at, warning_2_sent_at,
  last_synced_at, last_status, last_counts, last_error, robots_checked_at, created_at, updated_at
) on public.employer_job_feeds to authenticated;

create policy "members read their organisation's job feeds"
  on public.employer_job_feeds for select to authenticated
  using (public.is_org_member(organization_id));

create or replace function public.employer_job_feeds_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $t$
begin
  new.updated_at := pg_catalog.now();
  return new;
end
$t$;

create trigger employer_job_feeds_touch_updated_at
  before update on public.employer_job_feeds
  for each row execute function public.employer_job_feeds_touch_updated_at();

-- 2. The attempts -----------------------------------------------------------------------------------------------------------------------------
create table public.employer_job_feed_attempts (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id         uuid references public.profiles (id) on delete set null,
  host            text not null check (host = lower(host) and char_length(host) between 3 and 253),
  action          text not null check (action in ('preview', 'check_proof', 'connect', 'update_now')),
  result          text not null check (result ~ '^[a-z_]{1,40}$'),
  created_at      timestamptz not null default now()
);

comment on table public.employer_job_feed_attempts is
  '0246: one row per connect/check attempt (who, when, host, result; never the site-control code). The rate limits and the failed-attempts-per-host-per-day count read it as the service role. No client access.';

create index employer_job_feed_attempts_org_idx on public.employer_job_feed_attempts (organization_id, created_at desc);
create index employer_job_feed_attempts_host_idx on public.employer_job_feed_attempts (host, created_at desc);

alter table public.employer_job_feed_attempts enable row level security;
revoke all on table public.employer_job_feed_attempts from public, anon, authenticated;

-- 3. The marker columns on job_postings --------------------------------------------------------------------------------------------------------
alter table public.job_postings
  add column import_feed_id      uuid references public.employer_job_feeds (id),
  add column import_key          text,
  add column employer_closed_at  timestamptz;

alter table public.job_postings
  add constraint job_postings_import_pair check ((import_feed_id is null) = (import_key is null)),
  add constraint job_postings_import_is_internal check (import_feed_id is null or source_type = 'internal');

create unique index job_postings_import_unique on public.job_postings (import_feed_id, import_key) where import_feed_id is not null;
create index job_postings_import_feed_idx on public.job_postings (import_feed_id, status) where import_feed_id is not null;

comment on column public.job_postings.import_feed_id is
  '0246: set on a posting imported from an employer''s own careers page (employer_job_feeds). An imported posting is an internal row of the organisation, so the 0027 verified-organisation gate applies by itself, and it is link-out (apply on the employer''s own site). Never writable from a client.';
comment on column public.job_postings.import_key is
  '0246: the source''s own identifier for an imported posting (JSON-LD identifier, else its canonical URL). With import_feed_id it is unique, so a repeated sync updates in place. Not readable by anon or authenticated.';
comment on column public.job_postings.employer_closed_at is
  '0246: set when the employer closes an imported posting by hand; the sync skips reopening a posting that has it. Not readable by anon or authenticated.';

-- The INSERT policy is the only thing between a signed-in member and a forged imported posting (authenticated holds a table-level INSERT): the 0221 expression plus three conditions.
alter policy "org members can manage their org's internal postings" on public.job_postings
  with check (
    source_type = 'internal'::public.job_source_type
    and public.is_org_member(organization_id)
    and unlisted_at is null
    and removed_at is null
    and removal_reason is null
    and removed_by is null
    and admin_review_decision is null
    and admin_reviewed_at is null
    and admin_reviewed_by is null
    and banner_path is null
    and claimed_by_organization_id is null
    and claimed_at is null
    and import_feed_id is null
    and import_key is null
    and employer_closed_at is null
  );

-- The UPDATE policy: the 0190 expressions plus import_feed_id null in BOTH clauses.
alter policy "org members can update their org's internal postings" on public.job_postings
  using (
    source_type = 'internal'::public.job_source_type
    and public.is_org_member(organization_id)
    and status <> 'removed'::public.job_status
    and import_feed_id is null
  )
  with check (
    source_type = 'internal'::public.job_source_type
    and public.is_org_member(organization_id)
    and status in ('open'::public.job_status, 'closed'::public.job_status, 'draft'::public.job_status)
    and import_feed_id is null
  );

-- The pages need to know a posting is imported (to treat it as link-out); the bookkeeping columns stay internal (0218: a new column is readable only when a migration says so).
grant select (import_feed_id) on public.job_postings to anon, authenticated;

-- 4. The widget never lists an imported posting ------------------------------------------------------------------------------------------------
create or replace function public.org_job_widget(p_org_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $f$
declare
  v_name text;
  v_logo text;
  v_max  integer;
  v_jobs jsonb;
begin
  -- Every gate on the organisation, stated here because a DEFINER function does not inherit row level security.
  select o.name, o.logo_url, w.max_items
    into v_name, v_logo, v_max
    from public.organizations o
    join public.employer_widgets w on w.organization_id = o.id
    left join public.profiles c on c.id = o.created_by
   where o.id = p_org_id
     and o.verified
     and w.enabled
     and not public.is_qa_account(c.email, c.first_name, c.last_name, c.referral_leaderboard_display_name);
  if not found then
    return null;
  end if;

  -- Every gate on the postings. The explicit key list below is the whole output: nothing else can be added by accident.
  -- 0246: an IMPORTED posting (import_feed_id set) is never shown here, whatever its organisation: the widget lists the employer's own Talentrah postings only.
  select coalesce(jsonb_agg(
           jsonb_build_object(
             'id', x.id,
             'title', x.title,
             'location', x.location,
             'work_type', x.work_type::text,
             'employment_type', x.employment_type::text,
             'posted_at', x.posted_at
           ) order by x.posted_at desc, x.id desc
         ), '[]'::jsonb)
    into v_jobs
    from (
      select j.id, j.title, j.location, j.work_type, j.employment_type, j.posted_at
        from public.job_postings j
       where j.organization_id = p_org_id
         and j.source_type = 'internal'
         and j.import_feed_id is null
         and j.status = 'open'
         and j.removed_at is null
         and j.unlisted_at is null
         and j.superseded_at is null
         and (j.expires_at is null or j.expires_at > now())
       order by j.posted_at desc, j.id desc
       limit v_max
    ) x;

  return jsonb_build_object(
    'org', jsonb_build_object('name', v_name, 'logo_url', v_logo),
    'jobs', v_jobs
  );
end
$f$;

revoke execute on function public.org_job_widget(uuid) from public, anon, authenticated;
grant execute on function public.org_job_widget(uuid) to service_role;
comment on function public.org_job_widget(uuid) is
  '0237, amended by 0246: the public job-list widget''s one read. Returns NULL unless the organisation is verified, has its widget enabled and was not created by a QA account; otherwise {org:{name,logo_url}, jobs:[{id,title,location,work_type,employment_type,posted_at}]} for its open, listed, internal postings that were NOT imported, newest first, at most max_items. service_role only.';

-- 4b. Pruning the audit table: called by an existing daily route (service role only), never a new cron -----------------------------------------------------------
create or replace function public.prune_employer_job_feed_attempts(p_older_than interval default interval '30 days')
returns bigint
language plpgsql
security definer
set search_path = ''
as $f$
declare
  v_deleted bigint;
begin
  if p_older_than < interval '7 days' then
    raise exception 'prune_employer_job_feed_attempts: refusing to prune anything newer than 7 days (the failed-attempts-per-host-per-day count reads them)' using errcode = '22023';
  end if;
  delete from public.employer_job_feed_attempts where created_at < pg_catalog.now() - p_older_than;
  get diagnostics v_deleted = row_count;
  return v_deleted;
end
$f$;
revoke all on function public.prune_employer_job_feed_attempts(interval) from public, anon, authenticated;
grant execute on function public.prune_employer_job_feed_attempts(interval) to service_role;
comment on function public.prune_employer_job_feed_attempts(interval) is
  '0246: deletes connect/check attempts older than the interval (default 30 days, never less than 7). Returns the number deleted. service_role only; called by an existing daily route.';

-- 5. Self-check: the migration fails (and nothing is kept) unless all of this holds ------------------------------------------------------------
do $check$
begin
  if not (select relrowsecurity from pg_class where oid = 'public.employer_job_feeds'::regclass)
     or not (select relrowsecurity from pg_class where oid = 'public.employer_job_feed_attempts'::regclass) then
    raise exception '0246: row level security is not enabled on both new tables';
  end if;
  if has_table_privilege('authenticated', 'public.employer_job_feeds', 'INSERT') or has_any_column_privilege('authenticated', 'public.employer_job_feeds', 'INSERT')
     or has_table_privilege('authenticated', 'public.employer_job_feeds', 'UPDATE') or has_any_column_privilege('authenticated', 'public.employer_job_feeds', 'UPDATE')
     or has_table_privilege('authenticated', 'public.employer_job_feeds', 'DELETE')
     or has_table_privilege('anon', 'public.employer_job_feeds', 'SELECT') or has_any_column_privilege('anon', 'public.employer_job_feeds', 'SELECT') then
    raise exception '0246: employer_job_feeds grants more than a member SELECT';
  end if;
  if has_any_column_privilege('authenticated', 'public.employer_job_feed_attempts', 'SELECT')
     or has_any_column_privilege('authenticated', 'public.employer_job_feed_attempts', 'INSERT')
     or has_any_column_privilege('anon', 'public.employer_job_feed_attempts', 'SELECT') then
    raise exception '0246: employer_job_feed_attempts is reachable by an API role';
  end if;
  if not has_column_privilege('anon', 'public.job_postings', 'import_feed_id', 'SELECT')
     or has_column_privilege('anon', 'public.job_postings', 'import_key', 'SELECT')
     or has_column_privilege('authenticated', 'public.job_postings', 'import_key', 'SELECT')
     or has_column_privilege('anon', 'public.job_postings', 'employer_closed_at', 'SELECT')
     or has_column_privilege('authenticated', 'public.job_postings', 'employer_closed_at', 'SELECT') then
    raise exception '0246: job_postings column read grants are not as designed';
  end if;
  if has_column_privilege('authenticated', 'public.job_postings', 'import_feed_id', 'UPDATE')
     or has_column_privilege('authenticated', 'public.job_postings', 'import_key', 'UPDATE')
     or has_column_privilege('authenticated', 'public.job_postings', 'employer_closed_at', 'UPDATE') then
    raise exception '0246: a client can UPDATE an import marker column';
  end if;
  if not exists (
    select 1 from pg_policies
     where schemaname = 'public' and tablename = 'job_postings' and policyname = 'org members can manage their org''s internal postings'
       and cmd = 'INSERT' and with_check like '%import_feed_id IS NULL%' and with_check like '%import_key IS NULL%' and with_check like '%employer_closed_at IS NULL%'
  ) then
    raise exception '0246: the INSERT policy does not require the import markers to be null';
  end if;
  if not exists (
    select 1 from pg_policy
     where polrelid = 'public.job_postings'::regclass and polname = 'org members can update their org''s internal postings'
       and pg_get_expr(polqual, polrelid) like '%import_feed_id IS NULL%' and pg_get_expr(polwithcheck, polrelid) like '%import_feed_id IS NULL%'
  ) then
    raise exception '0246: the UPDATE policy does not require import_feed_id to be null in both USING and WITH CHECK';
  end if;
  if exists (select 1 from public.job_postings where import_feed_id is not null) then
    raise exception '0246: an imported posting exists before the feature does';
  end if;
end
$check$;
